~[?* "<guess>" [ "<n>" "<attr>" | "<n>" "<nom>" | "<v>" "<TD>" "<imp>" | "<v>" "<TD>" "<imp>" "<p2>" "<sg>" ] ] .o. [  [..] -> "<guess>" || "<guess>" ?* _ .#. .o. "<guess>" -> 0 || _ ?* "<guess>" .#. ];

